/**:
  ros__parameters:
    # The input GPIO pin number.
    pin: 13
    
    # The wheel diameter in centimeters.
    wheel_diameter: 13.0
    
    # The number of markers on the wheel.
    markers_per_rotation: 13
    
    # The publication rate of velocity report messages
    rate: 100.0
